---
- include_tasks: "Debian-lighttpd-modules.yml"
  with_items: "{{ lighttpd_modules }}"

- name: Enable the lighttpd service.
  service:
    name: "{{ lighttpd_service }}"
    state: "{{ lighttpd_state }}"
  notify: Restart lighttpd
  become: yes
