# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  # The most common configuration options are documented and commented below.
  # For a complete reference, please see the online documentation at
  # https://docs.vagrantup.com.

  # Every Vagrant development environment requires a box. You can search for
  # boxes at https://atlas.hashicorp.com/search.
  config.vm.box = "debian/stretch64"

  # Disable synced folders, to not have the Debian default install to not enter
  # an endless recursive dive starting from the symlink in test.
  config.vm.synced_folder ".", "/vagrant", disabled: true


  config.vm.define "lighttpd-server" do |machine|
    machine.vm.hostname = "lighttpd-server"
  end

  # define provisioning
  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "test.yml"
    ansible.raw_arguments = ['-v']
    ansible.host_vars = {
        "lighttpd-server" => {
        }
    }
  end
end
